/*
 * TransactionFormFrame.java
 *
 * Created on 15 décembre 2005, 10:56
 */

package org.paccman.ui.transactions.form;

import java.awt.CardLayout;
import org.paccman.ui.common.ValidateCancelListener;
import org.paccman.ui.main.Main;

/**
 *
 * @author  jfer
 */
public class TransactionFormFrame extends javax.swing.JDialog implements ValidateCancelListener {
    
    private static final String TRANSACTION_FORM_CARD = "TRANSACTION_FORM_CARD";
    private static final String SPLIT_FORM_CARD       = "SPLIT_FORM_CARD"      ;
    
    /** Creates new form TransactionFormFrame */
    public TransactionFormFrame() {
        super(Main.getMain());
        initComponents();
        setLocationRelativeTo(null);
        validateCancelPanel.addListener(this);
        ((CardLayout)transactionCardPanel.getLayout()).show(transactionCardPanel, TRANSACTION_FORM_CARD);
        
        // Initialize forms
//:TODO:        transactionFormPanel.setSplitFormPanel(splitFormPanel);
    }

    public void onValidateAction() {
        //:TODO:
    }

    public void onCancelAction() {
        //:TODO:
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validateCancelPanel = new org.paccman.ui.common.ValidateCancelPanel();
        transactionCardPanel = new javax.swing.JPanel();
        transactionFormPanel = new org.paccman.ui.transactions.form.TransactionFormPanel();
        splitFormPanel = new org.paccman.ui.transactions.form.SplitFormPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Transaction");
        setModal(true);
        getContentPane().add(validateCancelPanel, java.awt.BorderLayout.SOUTH);

        transactionCardPanel.setLayout(new java.awt.CardLayout());
        transactionCardPanel.add(transactionFormPanel, "TRANSACTION_FORM_CARD");

        javax.swing.GroupLayout splitFormPanelLayout = new javax.swing.GroupLayout(splitFormPanel);
        splitFormPanel.setLayout(splitFormPanelLayout);
        splitFormPanelLayout.setHorizontalGroup(
            splitFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        splitFormPanelLayout.setVerticalGroup(
            splitFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        transactionCardPanel.add(splitFormPanel, "SPLIT_FORM_CARD");

        getContentPane().add(transactionCardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.paccman.ui.transactions.form.SplitFormPanel splitFormPanel;
    private javax.swing.JPanel transactionCardPanel;
    private org.paccman.ui.transactions.form.TransactionFormPanel transactionFormPanel;
    private org.paccman.ui.common.ValidateCancelPanel validateCancelPanel;
    // End of variables declaration//GEN-END:variables
    
}
