package org.paccman.ui.common;
/*
 * PaddingBox.java
 *
 * Created on 4 octobre 2005, 09:01
 */

import java.awt.BorderLayout;
import javax.swing.JComponent;

/**
 *
 * @author  joao
 */
public class PaddingBox extends javax.swing.JPanel {
    
    JComponent component;
    
    /** Creates new form PaddingBox */
    public PaddingBox() {
        initComponents();
    }
    
    public void setComponent(JComponent component) {
        this.component = component;
        add(component, BorderLayout.CENTER);
        component.setVisible(visibleComponent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        showHideBtn = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.BorderLayout(5, 5));

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        titlePanel.setLayout(new java.awt.BorderLayout());

        titleLbl.setBackground(new java.awt.Color(204, 204, 204));
        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 14));
        titleLbl.setText("Title");
        titleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        titleLbl.setOpaque(true);
        titlePanel.add(titleLbl, java.awt.BorderLayout.CENTER);

        showHideBtn.setBackground(new java.awt.Color(204, 204, 204));
        showHideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/paddingbox_hide.png")));
        showHideBtn.setOpaque(true);
        showHideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showHideBtnMouseClicked(evt);
            }
        });

        titlePanel.add(showHideBtn, java.awt.BorderLayout.EAST);

        add(titlePanel, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    
    private void showHideBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showHideBtnMouseClicked
        setVisibleComponent(! visibleComponent );
    }//GEN-LAST:event_showHideBtnMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel showHideBtn;
    public javax.swing.JLabel titleLbl;
    public javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Getter for property title.
     * @return Value of property title.
     */
    public String getTitle() {
        return titleLbl.getText();
    }
    
    /**
     * Setter for property title.
     * @param title New value of property title.
     */
    public void setTitle(String title) {
        titleLbl.setText(title);
    }
    
    /**
     * Holds value of property visibleComponent.
     */
    private boolean visibleComponent = true;
    
    /**
     * Getter for property visibleComponent.
     * @return Value of property visibleComponent.
     */
    public boolean isVisibleComponent() {
        return this.visibleComponent;
    }
    
    /**
     * Setter for property visibleComponent.
     * @param visibleComponent New value of property visibleComponent.
     */
    public void setVisibleComponent(boolean visibleComponent) {
        this.visibleComponent = visibleComponent;
        if (component != null) {
            component.setVisible(visibleComponent);
        }
        showHideBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/" + (visibleComponent ? "paddingbox_hide.png" : "paddingbox_show.png" ))));    
    }
}

