/*
 * WelcomePane.java
 *
 * Created on 1 septembre 2005, 19:47
 */

package org.paccman.ui.welcome;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.Format;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;
import org.paccman.controller.PaccmanView;
import org.paccman.ui.welcome.accounts.AccountsPanel;
import org.paccman.ui.welcome.schedules.SchedulesPanel;

/**
 *
 * @author  joao
 */
public class WelcomePaneTab extends JPanel implements PaccmanView {
    
    /** Creates new form WelcomePane */
    public WelcomePaneTab() {
        initComponents();
        initMyComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        dateAndTimeLbl = new javax.swing.JLabel();
        updateDateAndTime();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        accountsPaddingBox = new org.paccman.ui.common.PaddingBox();
        accountsPaddingBox.setComponent(accountsPanel = new AccountsPanel());
        schedulesPaddingBox = new org.paccman.ui.common.PaddingBox();
        accountsPaddingBox.setComponent(accountsPanel = new AccountsPanel());

        setLayout(new java.awt.BorderLayout());

        headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        dateAndTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateAndTimeLbl.setText(" ");
        headerPanel.add(dateAndTimeLbl);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        accountsPaddingBox.setTitle("Accounts");
        accountsPaddingBox.setVisibleComponent(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(accountsPaddingBox, gridBagConstraints);

        schedulesPaddingBox.setTitle("Schedules");
        schedulesPaddingBox.setComponent(schedulesPanel = new SchedulesPanel());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(schedulesPaddingBox, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    private void initMyComponents() {
        // Starts a timer to update the date ans time label
        Timer timer = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                updateDateAndTime();
            }
        });
        timer.start();
    }
    
    void updateDateAndTime() {
        // Get today's date
        Date date = new Date();
        
        // Some examples
        Format formatter = DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM);
        String s = formatter.format(date);
        
        // Actually set the date
        dateAndTimeLbl.setText(s);
        
    }

    public void registerToDocumentCtrl() {
        accountsPanel.registerToDocumentCtrl();
        schedulesPanel.registerToDocumentCtrl();
    }
    
    public void onChange(org.paccman.controller.Controller controller) {
        // Nothing to do yet
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public org.paccman.ui.common.PaddingBox accountsPaddingBox;
    public javax.swing.JLabel dateAndTimeLbl;
    public javax.swing.JPanel headerPanel;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public org.paccman.ui.common.PaddingBox schedulesPaddingBox;
    // End of variables declaration//GEN-END:variables
    AccountsPanel   accountsPanel;
    SchedulesPanel  schedulesPanel;
    
}
