/*
 * Calculator.java
 *
 * Created on 6 mars 2006, 23:51
 */

package org.paccman.calc;

import java.util.prefs.Preferences;

/**
 *
 * @author  joao
 */
public class Calculator extends javax.swing.JPanel {

    boolean showTyping = true;

    public boolean getShowTyping() {
        return showTyping;
    }

    public void setShowTyping(boolean showTyping) {
        this.showTyping = showTyping;
        typingLbl.setVisible(showTyping);
    }

    /** Creates new form Calculator */
    public Calculator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        currentDisplayEdt = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        resetBtn = new org.paccman.calc.ResetBtn(this);
        clearEntryBtn1 = new org.paccman.calc.ClearEntryBtn(this);
        clearEntryBtn2 = new org.paccman.calc.ClearEntryBtn(this);
        clearEntryBtn3 = new org.paccman.calc.ClearEntryBtn(this);
        offBtn = new org.paccman.calc.ClearEntryBtn(this);
        _7Btn = new org.paccman.calc.CalcButton("7");
        _4Btn = new org.paccman.calc.CalcButton("4");
        _1Btn = new org.paccman.calc.CalcButton("1");
        _0Btn = new org.paccman.calc.CalcButton("0");
        equalButton = new org.paccman.calc.EqualButton(this);
        pointBtn = new org.paccman.calc.PointCalcButton(this);
        addBtn = new org.paccman.calc.OperCalcButton(this, "+");
        _8Btn = new org.paccman.calc.CalcButton("8");
        _9Btn = new org.paccman.calc.CalcButton("9");
        divBtn = new org.paccman.calc.OperCalcButton(this, "/");
        pcBtn = new org.paccman.calc.PcCalcButton(this);
        _5Btn = new org.paccman.calc.CalcButton("5");
        _6Btn = new org.paccman.calc.CalcButton("6");
        _3Btn = new org.paccman.calc.CalcButton("3");
        _2Btn = new org.paccman.calc.CalcButton("2");
        multBtn = new org.paccman.calc.OperCalcButton(this, "*");
        signButton = new org.paccman.calc.SignButton(this);
        minusBtn = new org.paccman.calc.OperCalcButton(this, "-");
        typingLbl = new javax.swing.JLabel();

        currentDisplayEdt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentDisplayEdt.setEditable(false);
        currentDisplayEdt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        currentDisplayEdt.setText("0");
        currentDisplayEdt.setFocusable(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        resetBtn.setText("RST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(resetBtn, gridBagConstraints);

        clearEntryBtn1.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn1, gridBagConstraints);

        clearEntryBtn2.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn2, gridBagConstraints);

        clearEntryBtn3.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn3, gridBagConstraints);

        offBtn.setText("Off");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(offBtn, gridBagConstraints);

        _7Btn.setText("7");
        _7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_7Btn, gridBagConstraints);

        _4Btn.setText("4");
        _4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_4Btn, gridBagConstraints);

        _1Btn.setText("1");
        _1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_1Btn, gridBagConstraints);

        _0Btn.setText("0");
        _0Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_0Btn, gridBagConstraints);

        equalButton.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(equalButton, gridBagConstraints);

        pointBtn.setText(".");
        pointBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(pointBtn, gridBagConstraints);

        addBtn.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(addBtn, gridBagConstraints);

        _8Btn.setText("8");
        _8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_8Btn, gridBagConstraints);

        _9Btn.setText("9");
        _9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_9Btn, gridBagConstraints);

        divBtn.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(divBtn, gridBagConstraints);

        pcBtn.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(pcBtn, gridBagConstraints);

        _5Btn.setText("5");
        _5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_5Btn, gridBagConstraints);

        _6Btn.setText("6");
        _6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_6Btn, gridBagConstraints);

        _3Btn.setText("3");
        _3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_3Btn, gridBagConstraints);

        _2Btn.setText("2");
        _2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_2Btn, gridBagConstraints);

        multBtn.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(multBtn, gridBagConstraints);

        signButton.setText("±");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(signButton, gridBagConstraints);

        minusBtn.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(minusBtn, gridBagConstraints);

        typingLbl.setText(" ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, currentDisplayEdt)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(typingLbl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .add(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(currentDisplayEdt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(typingLbl)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonPressed
        if ((evt.getSource() instanceof CalcButton) || (evt.getSource() instanceof OperCalcButton) || (evt.getSource() instanceof PointCalcButton)) {
            CalcButton cb = (CalcButton) evt.getSource();
            typingLbl.setText(typingLbl.getText() + cb.getKey());
        }
    }//GEN-LAST:event_calcButtonPressed
    //
    // Preferences
    //
    private static final String DEC_PRECISION = "DEC_PRECISION";
    static Preferences prefs = Preferences.userNodeForPackage(Calculator.class);

    static int getDecPrecision() {
        return prefs.getInt(DEC_PRECISION, 5);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.paccman.calc.CalcButton _0Btn;
    private org.paccman.calc.CalcButton _1Btn;
    private org.paccman.calc.CalcButton _2Btn;
    private org.paccman.calc.CalcButton _3Btn;
    private org.paccman.calc.CalcButton _4Btn;
    private org.paccman.calc.CalcButton _5Btn;
    private org.paccman.calc.CalcButton _6Btn;
    private org.paccman.calc.CalcButton _7Btn;
    private org.paccman.calc.CalcButton _8Btn;
    private org.paccman.calc.CalcButton _9Btn;
    private org.paccman.calc.OperCalcButton addBtn;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn1;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn2;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn3;
    private javax.swing.JFormattedTextField currentDisplayEdt;
    private org.paccman.calc.OperCalcButton divBtn;
    private org.paccman.calc.EqualButton equalButton;
    private javax.swing.JPanel jPanel1;
    private org.paccman.calc.OperCalcButton minusBtn;
    private org.paccman.calc.OperCalcButton multBtn;
    private org.paccman.calc.ClearEntryBtn offBtn;
    private org.paccman.calc.PcCalcButton pcBtn;
    private org.paccman.calc.PointCalcButton pointBtn;
    private org.paccman.calc.ResetBtn resetBtn;
    private org.paccman.calc.SignButton signButton;
    private javax.swing.JLabel typingLbl;
    // End of variables declaration//GEN-END:variables

}
