/*
 * Calculator.java
 *
 * Created on 6 mars 2006, 23:51
 */

package org.paccman.calc;

import java.util.prefs.Preferences;

/**
 *
 * @author  joao
 */
public class Calculator extends javax.swing.JPanel {
    
    /** Creates new form Calculator */
    public Calculator() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        currentDisplayEdt = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        resetBtn = new org.paccman.calc.ResetBtn();
        clearEntryBtn1 = new org.paccman.calc.ClearEntryBtn();
        clearEntryBtn2 = new org.paccman.calc.ClearEntryBtn();
        clearEntryBtn3 = new org.paccman.calc.ClearEntryBtn();
        clearEntryBtn4 = new org.paccman.calc.ClearEntryBtn();
        _7Btn = new org.paccman.calc.DigitCalcButton();
        _4Btn = new org.paccman.calc.DigitCalcButton();
        _1Btn = new org.paccman.calc.DigitCalcButton();
        _0Btn = new org.paccman.calc.DigitCalcButton();
        equalButton = new org.paccman.calc.EqualButton();
        pointBtn = new org.paccman.calc.PointCalcButton();
        addBtn = new org.paccman.calc.OperCalcButton();
        _8Btn = new org.paccman.calc.DigitCalcButton();
        _9Btn = new org.paccman.calc.DigitCalcButton();
        divBtn = new org.paccman.calc.OperCalcButton();
        pcBtn = new org.paccman.calc.PcCalcButton();
        _5Btn1 = new org.paccman.calc.DigitCalcButton();
        _6Btn1 = new org.paccman.calc.DigitCalcButton();
        _3Btn1 = new org.paccman.calc.DigitCalcButton();
        _8Btn1 = new org.paccman.calc.DigitCalcButton();
        multBtn = new org.paccman.calc.OperCalcButton();
        signButton = new org.paccman.calc.SignButton();
        minusBtn = new org.paccman.calc.OperCalcButton();

        currentDisplayEdt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        currentDisplayEdt.setEditable(false);
        currentDisplayEdt.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        currentDisplayEdt.setText("0");
        currentDisplayEdt.setFocusable(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        resetBtn.setText("RST");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(resetBtn, gridBagConstraints);

        clearEntryBtn1.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn1, gridBagConstraints);

        clearEntryBtn2.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn2, gridBagConstraints);

        clearEntryBtn3.setText("CE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn3, gridBagConstraints);

        clearEntryBtn4.setText("Off");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(clearEntryBtn4, gridBagConstraints);

        _7Btn.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_7Btn, gridBagConstraints);

        _4Btn.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_4Btn, gridBagConstraints);

        _1Btn.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_1Btn, gridBagConstraints);

        _0Btn.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_0Btn, gridBagConstraints);

        equalButton.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(equalButton, gridBagConstraints);

        pointBtn.setText(".");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(pointBtn, gridBagConstraints);

        addBtn.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(addBtn, gridBagConstraints);

        _8Btn.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_8Btn, gridBagConstraints);

        _9Btn.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_9Btn, gridBagConstraints);

        divBtn.setText("/");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(divBtn, gridBagConstraints);

        pcBtn.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(pcBtn, gridBagConstraints);

        _5Btn1.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_5Btn1, gridBagConstraints);

        _6Btn1.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_6Btn1, gridBagConstraints);

        _3Btn1.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_3Btn1, gridBagConstraints);

        _8Btn1.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(_8Btn1, gridBagConstraints);

        multBtn.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(multBtn, gridBagConstraints);

        signButton.setText("SIG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(signButton, gridBagConstraints);

        minusBtn.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanel1.add(minusBtn, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, currentDisplayEdt)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(currentDisplayEdt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //
    // Preferences
    //
    private static final String DEC_PRECISION = "DEC_PRECISION";

    static Preferences prefs = Preferences.userNodeForPackage(Calculator.class);

    static int getDecPrecision() {
        return prefs.getInt(DEC_PRECISION, 5);
    }

    
    public void updateDisplay(CalculatorParser.State currentState, StringBuffer operand_1, StringBuffer operand_2) {
        String sDisplay;
        switch (currentState) {
            
            case INIT:
                sDisplay = "0";
                break;
                
            case OPERAND_1:
            case OPERATOR_1:
            case EVALUATED:
            case OPERATOR_2:
                sDisplay = operand_1.toString();
                break;
                
            case OPERAND_2:
                sDisplay = operand_2.toString();
                break;
                
            default:
                sDisplay = "?";
                
        }
        currentDisplayEdt.setText(sDisplay);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.paccman.calc.DigitCalcButton _0Btn;
    private org.paccman.calc.DigitCalcButton _1Btn;
    private org.paccman.calc.DigitCalcButton _3Btn1;
    private org.paccman.calc.DigitCalcButton _4Btn;
    private org.paccman.calc.DigitCalcButton _5Btn1;
    private org.paccman.calc.DigitCalcButton _6Btn1;
    private org.paccman.calc.DigitCalcButton _7Btn;
    private org.paccman.calc.DigitCalcButton _8Btn;
    private org.paccman.calc.DigitCalcButton _8Btn1;
    private org.paccman.calc.DigitCalcButton _9Btn;
    private org.paccman.calc.OperCalcButton addBtn;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn1;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn2;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn3;
    private org.paccman.calc.ClearEntryBtn clearEntryBtn4;
    private javax.swing.JFormattedTextField currentDisplayEdt;
    private org.paccman.calc.OperCalcButton divBtn;
    private org.paccman.calc.EqualButton equalButton;
    private javax.swing.JPanel jPanel1;
    private org.paccman.calc.OperCalcButton minusBtn;
    private org.paccman.calc.OperCalcButton multBtn;
    private org.paccman.calc.PcCalcButton pcBtn;
    private org.paccman.calc.PointCalcButton pointBtn;
    private org.paccman.calc.ResetBtn resetBtn;
    private org.paccman.calc.SignButton signButton;
    // End of variables declaration//GEN-END:variables
    
}
