/*
 
    Copyright (C)    2005 Joao F. (joaof@sourceforge.net)
                     http://paccman.sourceforge.net
 
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 */

package org.paccman.ui.transactions.split;

import javax.swing.DefaultListCellRenderer;
import javax.swing.ListCellRenderer;
import org.paccman.controller.CategoryController;
import org.paccman.controller.SubCategoryController;

/**
 *
 * @author  joao
 */
public class CategoryComboBoxCellRenderer extends DefaultListCellRenderer implements ListCellRenderer {
    
    /** Creates new form BeanForm */
    public CategoryComboBoxCellRenderer() {
        initComponents();
    }
    
    public java.awt.Component getListCellRendererComponent(javax.swing.JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        String text;
        
        if (value instanceof SubCategoryController) {
            SubCategoryController scc = (SubCategoryController)value;
            if (index == -1) {
                // Currently selected item.
                String path = scc.getSubCategory().getParentCategory().toString();
                path += ":" + scc.toString();
                text = path;
            } else {
                String type = scc.getCategoryBase().isIncome() ? "+ " : "- ";
                text = "---- " + type + scc.getSubCategory().getName();
            }
        } else if (value instanceof CategoryController) {
            String type = ((CategoryController)value).getCategory().isIncome() ? "+ " : "- ";
            text = type + value.toString();
        } else if (value instanceof String) {
            text = (String)value;
        } else {
            assert value == null;
            text = " ";
        }
        
        DefaultListCellRenderer retVal = (DefaultListCellRenderer)super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        retVal.setText(text);
        
        return this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
