/*
 * PaymentMethodFormTab.java
 *
 * Created on 24 juin 2005, 00:06
 */

package org.paccman.ui.paymentmethods;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import org.paccman.controller.PaymentMethodController;
import org.paccman.ui.main.Main;
import org.paccman.ui.form.BadInputException;
import org.paccman.ui.selector.ControllerSelectionListener;

/**
 *
 * @author  joao
 */
public class PaymentMethodFormTab extends javax.swing.JPanel implements ControllerSelectionListener {
    
    /**
     * Creates new form PaymentMethodFormTab
     */
    public PaymentMethodFormTab() {
        initComponents();
        initMyComponents();
        setEditMode(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPaymentMethodSelectorPane = new javax.swing.JPanel();
        jEditNewPanel = new javax.swing.JPanel();
        jEditBtn = new javax.swing.JButton();
        jNewBtn = new javax.swing.JButton();
        jPaymentMethodFormPane = new javax.swing.JPanel();
        jValidateCancelPanel = new javax.swing.JPanel();
        jValidateBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPaymentMethodSelectorPane.setLayout(new java.awt.BorderLayout());

        jEditNewPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jEditBtn.setText("Edit");
        jEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditBtnActionPerformed(evt);
            }
        });

        jEditNewPanel.add(jEditBtn);

        jNewBtn.setText("New");
        jNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewBtnActionPerformed(evt);
            }
        });

        jEditNewPanel.add(jNewBtn);

        jPaymentMethodSelectorPane.add(jEditNewPanel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(jPaymentMethodSelectorPane);

        jPaymentMethodFormPane.setLayout(new java.awt.BorderLayout());

        jValidateCancelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jValidateBtn.setText("Validate");
        jValidateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidateBtnActionPerformed(evt);
            }
        });

        jValidateCancelPanel.add(jValidateBtn);

        jCancelBtn.setText("Cancel");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jValidateCancelPanel.add(jCancelBtn);

        jPaymentMethodFormPane.add(jValidateCancelPanel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPaymentMethodFormPane);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jValidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidateBtnActionPerformed
        PaymentMethodController validatedPaymentMethod = null;
        validatedPaymentMethod = (PaymentMethodController) jPaymentMethodFormPanel.onValidate();
        if ( validatedPaymentMethod != null) {
            setEditMode(false);
            if (validatedPaymentMethod == selectedPaymentMethod) {
                // PaymentMethod updated
                selectedPaymentMethod.notifyChange();
            } else {
                // New payment added
                Main.getDocumentCtrl().getDocument().addPaymentMethod(validatedPaymentMethod.getPaymentMethod());
                Main.getDocumentCtrl().notifyChange();
                jPaymentMethodSelectorPanel.selectPaymentMethod(validatedPaymentMethod);
            }
        } 
    }//GEN-LAST:event_jValidateBtnActionPerformed

    private void jEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditBtnActionPerformed
        jPaymentMethodFormPanel.onEdit();
        setEditMode(true);
    }//GEN-LAST:event_jEditBtnActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        jPaymentMethodFormPanel.onCancel();
        setEditMode(false);
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewBtnActionPerformed
        jPaymentMethodFormPanel.onNew();
        setEditMode(true);
    }//GEN-LAST:event_jNewBtnActionPerformed
    
    private boolean editing        ;
    private PaymentMethodController selectedPaymentMethod;
    
    public void setEditMode(boolean editing) {
        this.editing = editing;
        jEditBtn.setEnabled(!editing && (selectedPaymentMethod != null)); 
        jNewBtn.setEnabled(!editing);
        jValidateBtn.setEnabled(editing);
        jCancelBtn.setEnabled(editing); 
    }
    
    public void registerToDocumentCtrl() {
        jPaymentMethodSelectorPanel.registerToDocumentCtrl();
        jPaymentMethodFormPanel.registerToDocumentCtrl();
    }
    
    private void initMyComponents() {
        jPaymentMethodSelectorPanel = new PaymentMethodSelectorPanel();
        jPaymentMethodSelectorPane.add(jPaymentMethodSelectorPanel, BorderLayout.NORTH);
        
        jPaymentMethodFormPanel    = new PaymentMethodFormPanel();
        jPaymentMethodFormPane.add(jPaymentMethodFormPanel, BorderLayout.NORTH);
        
        jPaymentMethodSelectorPanel.addListener(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jEditBtn;
    private javax.swing.JPanel jEditNewPanel;
    private javax.swing.JButton jNewBtn;
    private javax.swing.JPanel jPaymentMethodFormPane;
    private javax.swing.JPanel jPaymentMethodSelectorPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jValidateBtn;
    private javax.swing.JPanel jValidateCancelPanel;
    // End of variables declaration//GEN-END:variables
    
    private PaymentMethodSelectorPanel jPaymentMethodSelectorPanel;
    private PaymentMethodFormPanel     jPaymentMethodFormPanel    ;
    
    public void controllerSelected(org.paccman.controller.Controller paymentMethodCtrl) {
        assert( ! editing );
        jPaymentMethodFormPanel.onSelect(paymentMethodCtrl);
        selectedPaymentMethod = (PaymentMethodController)paymentMethodCtrl;
        jEditBtn.setEnabled(true);
    }

    public boolean selectionEnabled() {
        if (editing) JOptionPane.showMessageDialog(this, "SELECTION DISABLE :TODO:"); 
        return ! editing;
    }

}
