/*
 * ValidateCancelPanel.java
 *
 * Created on 15 décembre 2005, 10:57
 */

package org.paccman.ui.common;

import org.paccman.ui.common.*;

/**
 *
 * @author  jfer
 */
public class ValidateCancelPanel extends javax.swing.JPanel {
    
    /** Creates new form ValidateCancelPanel */
    public ValidateCancelPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        validateBtn.setText("Validate");
        validateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateBtnActionPerformed(evt);
            }
        });
        add(validateBtn);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        add(cancelBtn);
    }// </editor-fold>//GEN-END:initComponents
    
    public void addListener(ValidateCancelListener vcl) {
        listenerList.add(ValidateCancelListener.class, vcl);
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        for (ValidateCancelListener vcl: getListeners(ValidateCancelListener.class)) {
            vcl.onCancelAction();
        }
    }//GEN-LAST:event_cancelBtnActionPerformed
    
    private void validateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateBtnActionPerformed
        for (ValidateCancelListener vcl: getListeners(ValidateCancelListener.class)) {
            vcl.onValidateAction();
        }
    }//GEN-LAST:event_validateBtnActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton validateBtn;
    // End of variables declaration//GEN-END:variables
    
}
