CREATE TABLE OBJ_PAYEES(
    PAYEE_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    NAME VARCHAR(100)
);

CREATE TABLE OBJ_PAYMENT_TYPES (
    PAYMENT_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    NAME VARCHAR(100)
);

CREATE TABLE OBJ_BANKS (
    BANK_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    NAME VARCHAR(100) NOT NULL,
    AGENCY VARCHAR(1024),
    ADDRESS_NUMBER VARCHAR(1024),
    ADDRESS_LINE1 VARCHAR(1024),
    ADDRESS_LINE2 VARCHAR(1024),
    ADDRESS_CITY VARCHAR(1024),
    ADDRESS_ZIP VARCHAR(1024),
    ADDRESS_COUNTRY VARCHAR(1024),
    TELEPHONE VARCHAR(1024),
    FAX VARCHAR(1024),
    INTERNET VARCHAR(1024),
    EMAIL VARCHAR(1024)
);


CREATE TABLE OBJ_TRANSACTIONS (
    TRANSACTION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    AMOUNT DECIMAL(20,10) NOT NULL,
    VALUE_DATE TIMESTAMP NOT NULL,
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    NOTE VARCHAR(1024),
    LABEL VARCHAR(1024),
    RECONCILIATION_STATE CHAR(1) NOT NULL DEFAULT 'U'
            -- <xsd:enumeration value="U"/> <!-- unreconciled -->
            -- <xsd:enumeration value="M"/> <!-- marked       -->
            -- <xsd:enumeration value="R"/> <!-- reconciled   -->
    CONSTRAINT RECONCILIATION_VALID_CONSTRAINT CHECK(RECONCILIATION_STATE IN ('U', 'M', 'R')),
    RECONCILIATION_DATE TIMESTAMP
);
