/*
 * PayeeFormPanel.java
 *
 * Created on 24 juin 2005, 00:34
 */

package org.paccman.ui.payees;

import org.paccman.controller.Controller;
import org.paccman.controller.PayeeController;
import org.paccman.paccman.Payee;
import org.paccman.ui.form.BadInputException;
import org.paccman.ui.form.PaccmanForm;

/**
 *
 * @author  joao
 */
public class PayeeFormPanel extends PaccmanForm {
    
    /**
     * Creates new form PayeeFormPanel
     */
    public PayeeFormPanel() {
        initComponents();
        setEditMode(false);
    }
    
    public void setForm(org.paccman.controller.Controller controller) {
        Payee payee = ((PayeeController)controller).getPayee();
        payeeNameEdt.setText(payee.getName());
    }
    
    public void setEditMode(boolean editing) {
        payeeNameEdt.setEnabled(editing);
    }
    
    public void registerToDocumentCtrl() {
    }
    
    public void clearForm() {
        payeeNameEdt.setText("");
    }
    
    public void getForm(org.paccman.controller.Controller controller) throws BadInputException {
        PayeeController payeeCtrl = (PayeeController)controller;
        // Name
        String name = payeeNameEdt.getText();
        payeeCtrl.getPayee().setName(name);
        
    }
    
    public org.paccman.controller.Controller getNewController() {
        return new PayeeController();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        nameLbl = new javax.swing.JLabel();
        payeeNameEdt = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(0, 2));

        nameLbl.setText("Name");
        add(nameLbl);

        payeeNameEdt.setEnabled(false);
        add(payeeNameEdt);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField payeeNameEdt;
    // End of variables declaration//GEN-END:variables
    
}
