/*
 * PaymentMethodFormPanel.java
 *
 * Created on 24 juin 2005, 00:34
 */

package org.paccman.ui.paymentmethods;

import org.paccman.controller.Controller;
import org.paccman.controller.PaymentMethodController;
import org.paccman.paccman.PaymentMethod;
import org.paccman.ui.form.BadInputException;
import org.paccman.ui.form.PaccmanForm;

/**
 *
 * @author  joao
 */
public class PaymentMethodFormPanel extends PaccmanForm {
    
    /**
     * Creates new form PaymentMethodFormPanel
     */
    public PaymentMethodFormPanel() {
        initComponents();
        setEditMode(false);
    }
    
    public void setForm(org.paccman.controller.Controller controller) {
        PaymentMethod paymentMethod = ((PaymentMethodController)controller).getPaymentMethod();
        paymentMethodNameEdt.setText(paymentMethod.getName());
    }
    
    public void setEditMode(boolean editing) {
        paymentMethodNameEdt.setEnabled(editing);
    }
    
    public void registerToDocumentCtrl() {
    }
    
    public void clearForm() {
        paymentMethodNameEdt.setText("");
    }
    
    public void getForm(org.paccman.controller.Controller controller) throws BadInputException {
        PaymentMethodController paymentMethodCtrl = (PaymentMethodController)controller;
        // Name
        String name = paymentMethodNameEdt.getText();
        paymentMethodCtrl.getPaymentMethod().setName(name);
        
    }
    
    public org.paccman.controller.Controller getNewController() {
        return new PaymentMethodController();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jNameLbl = new javax.swing.JLabel();
        paymentMethodNameEdt = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(0, 2));

        jNameLbl.setText("Name");
        add(jNameLbl);

        paymentMethodNameEdt.setEnabled(false);
        add(paymentMethodNameEdt);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jNameLbl;
    private javax.swing.JTextField paymentMethodNameEdt;
    // End of variables declaration//GEN-END:variables
    
}
