/*
 
    Copyright (C)    2005 Joao F. (joaof@sourceforge.net)
                     http://paccman.sourceforge.net 

    This program is free software; you can redistribute it and/or modify      
    it under the terms of the GNU General Public License as published by      
    the Free Software Foundation; either version 2 of the License, or         
    (at your option) any later version.                                       

    This program is distributed in the hope that it will be useful,           
    but WITHOUT ANY WARRANTY; without even the implied warranty of            
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             
    GNU General Public License for more details.                              

    You should have received a copy of the GNU General Public License         
    along with this program; if not, write to the Free Software               
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 
*/

package org.paccman.ui.welcome.schedules;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.event.MouseInputListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author  joao
 */
public class SchedulesPanel extends javax.swing.JPanel implements TableModelListener {
    
    /** Creates new form AccountsPanel */
    public SchedulesPanel() {
        initComponents();
        scheduledTablePanel.add(scheduledTable.getTableHeader(), BorderLayout.NORTH);
        scheduledTable.getModel().addTableModelListener(this);
    }

    public void registerToDocumentCtrl() {
        scheduledTable.getScheduledTableModel().registerToDocumentCtrl();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        noScheduledLbl = new javax.swing.JLabel();
        scheduledTablePanel = new javax.swing.JPanel();
        scheduledTable = new org.paccman.ui.welcome.schedules.ScheduledTable();

        setLayout(new java.awt.CardLayout());

        noScheduledLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noScheduledLbl.setText("No scheduled transaction.");
        add(noScheduledLbl, "NO_SCHEDULED_TRANSACTION");

        scheduledTablePanel.setLayout(new java.awt.BorderLayout());

        scheduledTablePanel.add(scheduledTable, java.awt.BorderLayout.CENTER);

        add(scheduledTablePanel, "SCHEDULED_TABLE");

    }// </editor-fold>//GEN-END:initComponents
    
    private static final String SCHEDULE_TABLE_CARD_NAME = "SCHEDULED_TABLE"         ;
    private static final String NO_SCHEDULED_CARD_NAME   = "NO_SCHEDULED_TRANSACTION";
    
    public void showCardPanel(ScheduledTableModel model) {
        if (model.getRowCount() > 0) {
            ((CardLayout)getLayout()).show(this, SCHEDULE_TABLE_CARD_NAME);
        } else {
            ((CardLayout)getLayout()).show(this, NO_SCHEDULED_CARD_NAME);
        }
    }

    public void tableChanged(TableModelEvent e) {
        assert e.getSource() instanceof ScheduledTableModel: "Only model should fire table change";
        showCardPanel((ScheduledTableModel)e.getSource());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel noScheduledLbl;
    public org.paccman.ui.welcome.schedules.ScheduledTable scheduledTable;
    public javax.swing.JPanel scheduledTablePanel;
    // End of variables declaration//GEN-END:variables
    
}
