/*
 * DateCellRenderer.java
 *
 * Created on 6 décembre 2005, 12:46
 */

package org.paccman.ui.common.table.renderer;

import java.awt.Component;
import java.text.DateFormat;
import java.util.Calendar;
import javax.swing.JTable;

/**
 *
 * @author  joao
 */
public class DateCellRenderer extends TableCellRenderer {
    
    /** Creates new form BeanForm */
    public DateCellRenderer() {
        initComponents();
    }

    static DateFormat formatter = DateFormat.getDateInstance(DateFormat.SHORT);

    public void setValue(Object value) {
        assert value instanceof Calendar: "Bad value type for column. Calendar expected.";
        Calendar cal = (Calendar)value;
        setText((value == null) ? "" : formatter.format(cal.getTime()));
    }

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        Component retValue;
        
        retValue = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        return retValue;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
