/*
 
    Copyright (C)    2005 Joao F. (joaof@sourceforge.net)
                     http://paccman.sourceforge.net 

    This program is free software; you can redistribute it and/or modify      
    it under the terms of the GNU General Public License as published by      
    the Free Software Foundation; either version 2 of the License, or         
    (at your option) any later version.                                       

    This program is distributed in the hope that it will be useful,           
    but WITHOUT ANY WARRANTY; without even the implied warranty of            
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             
    GNU General Public License for more details.                              

    You should have received a copy of the GNU General Public License         
    along with this program; if not, write to the Free Software               
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 
*/

package org.paccman.ui.main;

import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.paccman.preferences.ui.MainPrefs;
import org.paccman.ui.*;
import org.paccman.xml.PaccmanIOException;

/**
 *
 * @author  joao
 */
public class StartDialog extends javax.swing.JDialog {
    
    public enum Option { NEW_FILE, OPEN_FILE, CANCEL };
    
    Option startDialogOption;
    
    /** Creates new form StartDialog */
    StartDialog(Main main, boolean modal) {
        super(main, modal);
        initComponents();
        populateMruList();
    }
    
    Option selectedOption = Option.CANCEL;
    
    public Option doModal() {
        setVisible(true);
        return selectedOption;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        selectActionBtnGrp = new javax.swing.ButtonGroup();
        newFileRb = new javax.swing.JRadioButton();
        openFileRb = new javax.swing.JRadioButton();
        openPanel = new javax.swing.JPanel();
        selectedFileEdt = new javax.swing.JTextField();
        selectFileBtn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        mruList = new javax.swing.JList();
        cancelBtn = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        descriptionLbl = new javax.swing.JLabel();
        dontShowChb = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        selectActionBtnGrp.add(newFileRb);
        newFileRb.setSelected(true);
        newFileRb.setText("Create a new account file");
        newFileRb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        newFileRb.setMargin(new java.awt.Insets(0, 0, 0, 0));

        selectActionBtnGrp.add(openFileRb);
        openFileRb.setText("Open an existing account file");
        openFileRb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        openFileRb.setMargin(new java.awt.Insets(0, 0, 0, 0));

        openPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        selectFileBtn.setText("...");
        selectFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileBtnActionPerformed(evt);
            }
        });

        mruList.setModel(new DefaultListModel());
        mruList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mruList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mruListValueChanged(evt);
            }
        });

        jScrollPane.setViewportView(mruList);

        org.jdesktop.layout.GroupLayout openPanelLayout = new org.jdesktop.layout.GroupLayout(openPanel);
        openPanel.setLayout(openPanelLayout);
        openPanelLayout.setHorizontalGroup(
            openPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, openPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(openPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, openPanelLayout.createSequentialGroup()
                        .add(selectedFileEdt, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(selectFileBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        openPanelLayout.setVerticalGroup(
            openPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, openPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(openPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(selectFileBtn)
                    .add(selectedFileEdt, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        openPanelLayout.linkSize(new java.awt.Component[] {selectFileBtn, selectedFileEdt}, org.jdesktop.layout.GroupLayout.VERTICAL);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        descriptionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLbl.setText("Select what you would like to do.");

        dontShowChb.setText("Don't show this window anymore");
        dontShowChb.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dontShowChb.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(okBtn)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(cancelBtn))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(4, 4, 4)
                                .add(openFileRb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, descriptionLbl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(4, 4, 4)
                                        .add(newFileRb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(openPanel)
                            .add(dontShowChb, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                        .add(8, 8, 8))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(descriptionLbl)
                .add(13, 13, 13)
                .add(newFileRb)
                .add(12, 12, 12)
                .add(openFileRb)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(openPanel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dontShowChb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(cancelBtn)
                    .add(okBtn))
                .addContainerGap())
        );
        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void mruListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mruListValueChanged
        fileSelected((String)(mruList.getSelectedValue()));
    }//GEN-LAST:event_mruListValueChanged

    private void fileSelected(String filename) {
        selectedFileEdt.setText(filename);
        openFileRb.setSelected(true);
    }
    
    private void populateMruList() {
        int size = MainPrefs.getMruSize();
        DefaultListModel model = (DefaultListModel)mruList.getModel();
        for (int i = 0 ; i < size ; i++ ) {
            model.addElement(MainPrefs.getMruFile(i));
        }
    }
    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        if (newFileRb.isSelected()) {
            endDialog(Option.NEW_FILE);
        } else if (openFileRb.isSelected()) {
            String filename = selectedFileEdt.getText();
	    if (filename.length() == 0) {
		JOptionPane.showMessageDialog(this, "Select a file to open.",
			java.util.ResourceBundle.getBundle("org/paccman/ui/i18n/start_dialog").getString("Error"), JOptionPane.ERROR_MESSAGE);
		return;
	    }
//	    try {
////:TODO:		((Main)getParent()).openFile(new File(filename));
//	    } catch (PaccmanIOException pie) {
//		String errorMessage = java.util.ResourceBundle.getBundle("org/paccman/ui/i18n/start_dialog").getString("Failed_to_open_file_") + filename;
//		errorMessage += " [" + pie.getMessage() + "]"; //:TODO:
//		JOptionPane.showMessageDialog(this, errorMessage,
//			java.util.ResourceBundle.getBundle("org/paccman/ui/i18n/start_dialog").getString("Error"), JOptionPane.ERROR_MESSAGE);
//		return;
//	    }
	    endDialog(Option.OPEN_FILE);
	} else {
	    assert false: "Choice not handled";
	}
    }//GEN-LAST:event_okBtnActionPerformed

    private void endDialog(Option option) {
        selectedOption = option;
        MainPrefs.setShowStartDialog(!dontShowChb.isSelected());
        dispose();
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        endDialog(Option.CANCEL);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void selectFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileBtnActionPerformed
        PaccmanFileChooser pfc = new PaccmanFileChooser();
        
        if (pfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            selectedFileEdt.setText(pfc.getSelectedFile().getAbsolutePath());
            openFileRb.setSelected(true);
        }
    }//GEN-LAST:event_selectFileBtnActionPerformed
    
    public String getSelectedFile() {
        return selectedFileEdt.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JCheckBox dontShowChb;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JList mruList;
    private javax.swing.JRadioButton newFileRb;
    private javax.swing.JButton okBtn;
    private javax.swing.JRadioButton openFileRb;
    private javax.swing.JPanel openPanel;
    private javax.swing.ButtonGroup selectActionBtnGrp;
    private javax.swing.JButton selectFileBtn;
    private javax.swing.JTextField selectedFileEdt;
    // End of variables declaration//GEN-END:variables
    
}
