/*
 * StatusCellRenderer.java
 *
 * Created on 6 décembre 2005, 16:50
 */

package org.paccman.ui.transactions.table;

import java.awt.Color;
import org.paccman.paccman.TransactionBase;
import org.paccman.ui.common.table.renderer.ITableCellRenderer;

/**
 *
 * @author  jfer
 */
public class StatusCellRenderer extends org.paccman.ui.common.table.renderer.TableCellRenderer implements ITableCellRenderer {
    
    /** Creates new form BeanForm */
    public StatusCellRenderer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/reconciled_reconciled.png")));
    }// </editor-fold>//GEN-END:initComponents

    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        
        java.awt.Component retValue;
        
        TransactionBase.ReconciliationState state = (TransactionBase.ReconciliationState)value;
        switch (state) {
            
            case RECONCILED:
                setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/reconciled_reconciled.png")));
                break;
                
            case MARKED:
                setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/reconciled_marked.png")));
                break;
                
            default:
                setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/paccman/ui/resources/images/reconciled_normal.png")));
                break;
                
        }
        
        retValue = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        setText("");
        
        return retValue;

    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    // ------------------------------------------------------------------------------------
    // Delegation functions (java does not support multiple inheritance)
    //
    private final ITableCellRenderer cellRenderer = new TransactionTableCellRenderer(this);
    public Color getBkColor(int row, int column, boolean isSelected) {
        return cellRenderer.getBkColor(row, column, isSelected);
    }
    //
    // ------------------------------------------------------------------------------------
    
}
