/*
 
    Copyright (C)    2005 Joao F. (joaof@sourceforge.net)
                     http://paccman.sourceforge.net 

    This program is free software; you can redistribute it and/or modify      
    it under the terms of the GNU General Public License as published by      
    the Free Software Foundation; either version 2 of the License, or         
    (at your option) any later version.                                       

    This program is distributed in the hope that it will be useful,           
    but WITHOUT ANY WARRANTY; without even the implied warranty of            
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             
    GNU General Public License for more details.                              

    You should have received a copy of the GNU General Public License         
    along with this program; if not, write to the Free Software               
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 
*/

package org.paccman.ui;

import javax.swing.JFrame;
import org.paccman.controller.DocumentController;
import org.paccman.controller.PaccmanView;

/**
 *
 * @author  joao
 */
public class PropertiesFrame extends JFrame implements PaccmanView {
    
    /** Creates new form PropertiesFrame */
    public PropertiesFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        titleEdt = new javax.swing.JTextField();
        closeBtn = new javax.swing.JButton();
        fileLbl = new javax.swing.JLabel();
        fileEdt = new javax.swing.JTextField();
        fileVersionLbl = new javax.swing.JLabel();
        fileVersionEdt = new javax.swing.JTextField();
        creationDateLbl = new javax.swing.JLabel();
        creationDateEdt = new javax.swing.JTextField();
        lastUpdateLbl = new javax.swing.JLabel();
        lastUpdateEdt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account file properties");

        titleLbl.setText("Title");

        titleEdt.setEnabled(false);

        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        fileLbl.setText("File");

        fileEdt.setEnabled(false);

        fileVersionLbl.setText("File version");

        fileVersionEdt.setEnabled(false);

        creationDateLbl.setText("Creation date");

        creationDateEdt.setEnabled(false);

        lastUpdateLbl.setText("Last update");

        lastUpdateEdt.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileVersionLbl)
                            .addComponent(titleLbl)
                            .addComponent(fileLbl)
                            .addComponent(creationDateLbl)
                            .addComponent(lastUpdateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(titleEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(fileVersionEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(creationDateEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(lastUpdateEdt, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
                    .addComponent(closeBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileLbl)
                    .addComponent(fileEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleEdt)
                    .addComponent(titleLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileVersionLbl)
                    .addComponent(fileVersionEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creationDateLbl)
                    .addComponent(creationDateEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastUpdateLbl)
                    .addComponent(lastUpdateEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeBtn)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {titleEdt, titleLbl});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed
    
    public void onChange(org.paccman.controller.Controller controller) {
        DocumentController docCtrl =(DocumentController)controller;
        titleEdt.setText(docCtrl.getDocument().getTitle());
        if (docCtrl.getFile() != null) {
            // Document may not have a file yet (case of a new document)
            fileEdt.setText(docCtrl.getFile().getAbsolutePath());
            fileVersionEdt.setText(docCtrl.getLoadVersion());
            creationDateEdt.setText(docCtrl.getDocument().getCreationDate().getTime().toString());
            lastUpdateEdt.setText(docCtrl.getDocument().getLastUpdateDate().getTime().toString());
        } else {
            fileEdt.setText("(not saved yet)");
            fileVersionEdt.setText("(not saved yet)");
            creationDateEdt.setText("(not saved yet)");
            lastUpdateEdt.setText("(not saved yet)");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton closeBtn;
    public javax.swing.JTextField creationDateEdt;
    public javax.swing.JLabel creationDateLbl;
    public javax.swing.JTextField fileEdt;
    public javax.swing.JLabel fileLbl;
    public javax.swing.JTextField fileVersionEdt;
    public javax.swing.JLabel fileVersionLbl;
    public javax.swing.JTextField lastUpdateEdt;
    public javax.swing.JLabel lastUpdateLbl;
    public javax.swing.JTextField titleEdt;
    public javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
    
}
