package org.paccman.ui.welcome;

import org.jdesktop.swingx.JXTaskPaneContainer;

/**
 *
 * @author joaof (joaof at sourceforge.net)
 */
public class WelcomePanel extends JXTaskPaneContainer {

    /** Creates new form WelcomePanel */
    public WelcomePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acountTaskPane = new org.jdesktop.swingx.JXTaskPane();
        schedulesTaskPane = new org.jdesktop.swingx.JXTaskPane();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.paccman.ui.main.Main.class).getContext().getResourceMap(WelcomePanel.class);
        acountTaskPane.setTitle(resourceMap.getString("acountTaskPane.title")); // NOI18N
        acountTaskPane.setName("acountTaskPane"); // NOI18N

        schedulesTaskPane.setTitle(resourceMap.getString("schedulesTaskPane.title")); // NOI18N
        schedulesTaskPane.setName("schedulesTaskPane"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(acountTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(schedulesTaskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(acountTaskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schedulesTaskPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTaskPane acountTaskPane;
    private org.jdesktop.swingx.JXTaskPane schedulesTaskPane;
    // End of variables declaration//GEN-END:variables

}
