/*
 
    Copyright (C)    2005 Joao F. (joaof@sourceforge.net)
                     http://paccman.sourceforge.net 

    This program is free software; you can redistribute it and/or modify      
    it under the terms of the GNU General Public License as published by      
    the Free Software Foundation; either version 2 of the License, or         
    (at your option) any later version.                                       

    This program is distributed in the hope that it will be useful,           
    but WITHOUT ANY WARRANTY; without even the implied warranty of            
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             
    GNU General Public License for more details.                              

    You should have received a copy of the GNU General Public License         
    along with this program; if not, write to the Free Software               
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 
*/

package org.paccman.ui.banks;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import org.paccman.controller.BankController;
import org.paccman.ui.selector.ControllerSelectionListener;
import static org.paccman.ui.main.ContextMain.*;

/**
 *
 * @author  joao
 */
public class BankFormTab extends javax.swing.JPanel implements ControllerSelectionListener {
    
    /**
     * Creates new form BankFormTab
     */
    public BankFormTab() {
        initComponents();
        initMyComponents();
        setEditMode(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jBankSelectorPane = new javax.swing.JPanel();
        jEditNewPanel = new javax.swing.JPanel();
        jEditBtn = new javax.swing.JButton();
        jNewBtn = new javax.swing.JButton();
        jBankFormPane = new javax.swing.JPanel();
        jValidateCancelPanel = new javax.swing.JPanel();
        jValidateBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        mainScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jBankSelectorPane.setLayout(new java.awt.BorderLayout());

        jEditNewPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jEditBtn.setText("Edit");
        jEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditBtnActionPerformed(evt);
            }
        });

        jEditNewPanel.add(jEditBtn);

        jNewBtn.setText("New");
        jNewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewBtnActionPerformed(evt);
            }
        });

        jEditNewPanel.add(jNewBtn);

        jBankSelectorPane.add(jEditNewPanel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(jBankSelectorPane);

        jBankFormPane.setLayout(new java.awt.BorderLayout());

        jValidateCancelPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jValidateBtn.setText("Validate");
        jValidateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValidateBtnActionPerformed(evt);
            }
        });

        jValidateCancelPanel.add(jValidateBtn);

        jCancelBtn.setText("Cancel");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jValidateCancelPanel.add(jCancelBtn);

        jBankFormPane.add(jValidateCancelPanel, java.awt.BorderLayout.SOUTH);

        jBankFormPane.add(mainScrollPane, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jBankFormPane);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jValidateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValidateBtnActionPerformed
        BankController validatedBank = null;
        validatedBank = (BankController) jBankFormPanel.onValidate();
        if ( validatedBank != null) {
            setEditMode(false);
            if (validatedBank == selectedBank) {
                // Bank updated
                selectedBank.notifyChange();
            } else {
                // New bank added
                    getDocumentController().getDocument().addBank(validatedBank.getBank());
                getDocumentController().notifyChange();
                jBankSelectorPanel.selectBank(validatedBank);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to validate", "Validation failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jValidateBtnActionPerformed

    private void jEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditBtnActionPerformed
        jBankFormPanel.onEdit();
        setEditMode(true);
    }//GEN-LAST:event_jEditBtnActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        jBankFormPanel.onCancel();
        setEditMode(false);
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jNewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewBtnActionPerformed
        jBankFormPanel.onNew();
        setEditMode(true);
    }//GEN-LAST:event_jNewBtnActionPerformed
    
    private boolean editing        ;
    private BankController selectedBank;
    
    public void setEditMode(boolean editing) {
        this.editing = editing;
        jEditBtn.setEnabled(!editing && (selectedBank != null)); 
        jNewBtn.setEnabled(!editing);
        jValidateBtn.setEnabled(editing);
        jCancelBtn.setEnabled(editing); 
    }
    
    public void registerToDocumentCtrl() {
        jBankSelectorPanel.registerToDocumentCtrl();
        jBankFormPanel.registerToDocumentCtrl();
    }
    
    private void initMyComponents() {
        jBankSelectorPanel = new BankSelectorPanel();
        jBankSelectorPane.add(jBankSelectorPanel, BorderLayout.NORTH);
        
        jBankFormPanel    = new BankFormPanel();
        mainScrollPane.setViewportView(jBankFormPanel);

	jBankSelectorPanel.addListener(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBankFormPane;
    private javax.swing.JPanel jBankSelectorPane;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JButton jEditBtn;
    private javax.swing.JPanel jEditNewPanel;
    private javax.swing.JButton jNewBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jValidateBtn;
    private javax.swing.JPanel jValidateCancelPanel;
    private javax.swing.JScrollPane mainScrollPane;
    // End of variables declaration//GEN-END:variables
    
    private BankSelectorPanel jBankSelectorPanel;
    private BankFormPanel     jBankFormPanel    ;
    
    public void controllerSelected(org.paccman.controller.Controller bankCtrl) {
        assert( ! editing );
        jBankFormPanel.onSelect(bankCtrl);
        selectedBank = (BankController)bankCtrl;
        jEditBtn.setEnabled(true);
    }

    public boolean selectionEnabled() {
        return ! editing;
    }

}
